sudo: required

services:
  - docker

script:
  - docker build -t taiga-back .
  - docker run --name postgres -e POSTGRES_USER=taiga -e POSTGRES_PASSWORD=Un1c0rn -e POSTGRES_NAME=taiga -d postgres
  - docker run --name taiback --link postgres -d taiga-back
  - docker exec taiback /bin/bash -c "apt-get update && apt-get install -y curl && while ! nc -z localhost 8000; do echo 'Waiting for database being populated...'; sleep 2; done && curl localhost:8000"

  
